### ISSUE TITLE
Incorrect rule name ?

### ISSUE THREAD

**Issue by mrseanryan** [wcandillon/eslint-plugin-ts-exports#1]
thanks for making this plugin!

From the code, it looks another rule name is in use?

```
  name: "js-function-in-worklet",
  meta: {
    type: "problem",
    docs: {
      description:
        "non-worklet functions should be invoked via runOnJS. Use runOnJS() or workletlize instead.",
```

I guess that would show the wrong rule name, if the rule fails ?

**Comment by wcandillon** [comment]
@mrseanryan Thank you for catching this, fixed it in master, it's currently deploying v1.0.5. Feel free to reopen if you find other such artifacts.
